inherit_from: .rubocop_todo.yml

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
