language: ruby
cache: bundler

install:
  - bundle install --path vendor/bundle

script:
  - rake lint
  - rake test

after_script:
  - curl -sL scripts.piet.me/ci/release | bash

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  on:
    tags: true

env:
  global:
    secure: f49uAglcexjs3ahc+pb6od/hSP7trSU2OiXafO11mjRIQyoT16pSjRtQPwjGL6Cq128n7DTWpX46ja2KQMAK6BD9IpOOeN3SOGyeIfIMT3p7/3iEPul/M6q6ohjimWniEyU63qlGd6D2gfG2DiguVl/f++/U6lpcByIsyxM6Skz3q3trdha0cOQwkm6Q04cuaw53U30nvOv9VPR7GerY7/aARs7vwNUXpqVVPoFgosrJLuL2/9Zuzt8gUqGL9zjmOEL2SePXC1whoowmJr5PcAZZUTbf812NWf0aQY8ZQl8IPIxcOS19UuL7AtT4ynPjAnDSTafItWaNzlGm+DuPaP+xt7ZQ6hg1TZkA83Phy+HCreGQH/SUWblOuxgU+yRj8uFYeLlL7LDrlAqzX0GsyEgLizd3j3rdnR25VYGMnNzpxj09Z1wruMSzZv17IKe4IDLH796c0nUHL8/joJ3RpMQuCXt36vxUuS1TpaMMOBsuyni0x6QM2IDXGpn0c1cSA7xQ9QB8MqIzfKgGl1fQ960n1moYufVUCbbC/WELkR3N/BTn0TYP/+jqgCWmBl0cyDVeI7mw7R8wO2vhJmRkeHXJ74euxEBppBgIn3r3CBlZqZ15PYXqAjEg6Eb5PyebGj2qHoOs2BNLZKCYy9Mfmk7VfLwRfjWZA7TRTl4pJHc=
