language: python
script:
- echo $FOO
env:
  global:
    secure: kZb3tBq/PdsXKyjC0Opih5d6WVaucmQ/UOhYlTwWOL10zCpgJmTFUmLDDXljR0NnqU++OCByVxFIamF9VNm0keU6gXtd3P63l/OaS1oA4voZCIJA3R62s4SkSV5U9lT+eMA0za0FpOs0Hq6dZ1uuLxUVcfgxfNMQZlFcz1uUCzD3VXIrB9shC5iETr1mgOWEwp37mtUM3juvVKL18dAdw8BKTE7VivTE+0kxaLZt7M3GEQchSkxiTOxzZPMlWVLUYCdwW1aZaboH+2ZjwCo2j39zuF4hmHZ9zyoNrEAPUwIceiar5PmBt+a5o6uJ2BKlSfsG5LDGXcpcUbhLnhjaJNE4aZu1cew2bjOJAmtgiKbOok07IU6C5sc0owL0RS5Bp69FwnhoHazFfXC7Tjaq9J+Hz7Gko8DFPhJb0x7avcVWwDVql3xUyvfib60OqF4jL7wfXuO5x1VXW2UUDeS0NkV8K3vWxs5dkG8lcwZ3K3gWReWdGt1+f+X+/rE3b/U/sNL1J6vafeXsfY3c43spu+/Ye+VFa2wBxF8wiiYORGAhVXifGf2rZy4Xm6pd76QHTMEOM0Fi5l26u8BiqAbaaLjmU8K1lQBKhez/IxDwNB43VoLpih0dxetsirZufgJNB5U9AUvMcx+4z96pBa0UwYCT/pIhfVxYT8o6HxYeaT0=
