language: ruby
cache: bundler
install:
  - bundle install --path vendor/bundle
script:
  - rake lint
  - rake test
after_script:
  - curl -sL scripts.piet.me/ci/release | bash
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  on:
    tags: true
env:
  global:
    secure: KSAQCUSc4loLFxGmdlc94REPMgwZhmowyoFcKSedMVVTJLQhcc+uPLHDcGRX3JCN8mnOa4wrnv2sgSUfZyLTztUnUBZo5XS7dF9zv9xzEuAhMH8Aqtk24Fab0cJlBrYGXWZDqb9qjPMSxuWACjEN5czhH7+b7FBcqisTgkWXqHXOJN6sWU2fZqMNADKtMQsC9R9x6vE6Beq7+eN5D1c560pzTIQXV+bcC5ffTUBvBMpSMLmiYrh2+Au+pkWslVgZ7Xw36sh/uSauoLnKPecXgRnO2mDwmi1BbjNiS7b/p8f7/2lfLyi6PAI93IsasWmb1OPIS58ecO8FH22BR5n/9bZjQ27+mfB4H6hnTiFIxpVI47Ln8p8ADm/dArST9SljtOv93IToOKkCzrpXC3SCNVST1c2rr5F2ntJpBfDuloK16nMsHPVIJj082XfbYrjfyZIupxKXt3t3H7FOtiuHhbZBRAnd72ZdguPa2U1fVqmxgsx+oVjf7u5mTMfxfDwHGQRLMivCY9OyZwZfo1PGruQ2SlA4ITngXUHmAcF5Wvp65Qa6jc1fZa/hQRPY56aQty59n2F+IaBWgaljm9e4wwG8mfhH69+YcO3NcwP+T72/lhqS60eoorMCKFjxJbWIUo4IidWVFaulOvna9HdLudClPs4oVQo7IUSd0umTXJ4=
