language: python
script:
- echo $FOO
env:
  global:
    secure: GZO6E7OPGRrlZgAR9/EDWNrHLvnUJHX26xlYfTC4uNl73e7klHNEDEh6nV6ynLMc8LFqaOf8b0zp+eW0F68XK9TEIuirD8LaoUQjuGJjgQHtLTG9OgeB9EIeSGoPSYX1t9huBgTBoQMrJ4rI8i6LZiaKQVpofch1my0ut2FKvV2Ooe9nkKIko5kKzlKAWLp1mZN1WhZlXPX6A4KqrgPk1esJYeAwJ7rtWQL6O4vTHGuR/YsC3RT+rozGYfJp5h2BvXwdxzlL+eASsHIOikUE0Lyisgd8O4po5L9j/s1Q0wjqCh6St1OVfvmPUsAuZZ/HKVmuT7BhGv5NVjMuaMkUdb+q2S2N9/eARFpXvYwkYkXg7crt921cGlzpv7AdLals3sMk1gCTPzmqMBdXzwt6euArpstndOuq0l97sZqqcaqZ4lHFHyw1hneM/LR8IA+hX5ym2dxN2BanoqxCJ0m69xXLN8kwlOGB7hdmoj7ve4ygKytp1YDjcrgxNjI4XIUDURUzh46V0ZqL/+i8XFd+1FiGeF2d1t1L+1i4tcw1p0MbsIW+aRcX+PuAu00oe+MyUA0Wgz54ANJBGVF/bcuZo/4pJIaAaxa4R+vq/b4xWa5iBHPCQHZB1QOc3E5U3sX3GEV5m9A4XGtP60Ybt6xOHZ3Cw6ovyndRhBDaV7q9zLA=
