language: python
script:
- echo $FOO: 
env:
  global:
    secure: D5hE6PyOesvqCHuoL/Dwpr95SP4WuIDpLsxp2lAo/5/Ff1/FAYa5KMcnQjZvAlTpCbgwMZAX4cKXoz1fHH8BYTb9zleBLzhf+ieeANPDmYAOXzORJ/EA+zh2mrXUiZB7jrpkiBsj6yUJxYcaUBUtl6O4F6BkiVMApIHgObCgHza+FmML7Vz8RvpVBC0/O5YsrmheOHiQZhiCyfIIiyrhVKv8VfDSqwi4PYaUdam3sCDLquzIrcqBrgmyb/9ZhMWV+GGXeBbXRkKm8mjGOQU6GxBTX1Fdkj7fI4aogiqpt6BXAczGB8KIz1HihKIjFk6PVTjYDvDY1l2V4d+h+lYuG5gKAdt5ZKF9HX4sSo0Q7fTMt7LN70Gm8/DWxZmH0q1Em1Ij16LYHfLHqk1t3n15o5dypIM4pBo94xwT67l8WxfnNIeZ6qU+eK0XsoiWHSAKY4LZx85Z2mdEH/P5Cf62SySXJFLjdupgE9Ol9kRgNdB/zsy8t/WiXEUv8s6GsIJx7+8JRK+M5AsexED5J9CmNrqt7+1wTkVN0aJqRbqgA+mfeJftR/P3t7cocFG/zUvY1NTXJqMsvN6BvnY3EwrVzDceuNeXB5d5tq3yVi1uejD1OEQrdSlC0ayWd4iQxHr3/YrcT7HyRH02P/mv4WnAcXYFve8xLl1iOaJbuVYVbP0=
