language: python
script:
- echo $FOO:
env:
  global:
    secure: S2CnBV+QhJ02lodnKbE8iMhBdaXBS7d1CrMecOu098RHFm6IandqeK/DLBWFJHmh+EPI2XBvB4IG3FlaL1fr0A6W149IoCr18c26Vlk+yAkEqNwDk40aWu0OdiFbLbLe64C3NAnanXIclI+oy9Tu6tt1iabGQJ8Tp6ps+7hDTl17S/4hQ1K5RDnt2XsCPkMJStloK003lC1YXkvUWRHXj51MzWU+C8iIos2i2gWSugA400GOC2Mz4ID98rZi90ZUGU46Ey5EeJ1e+NMF8GTb8u+NVRrjbpeoXE1smY88KiJ4lf3OosI/qEiw6Oj1vCPkBqVV+HgKbSKiCn/FN4/egGl/1VZqlzvYDXE8f3LePOKCXGhKvKK/h45D56wsOnq1X14Hf6PRhbgFsguQvjt49KE0S208POTc3ugCUSDGBR5949b8mSzFw/mjh4J9QJciaQChqAIi80ZQ7yRlm9cmQDekeLsMg4tz4NUXZZX+5NwcXcMh2OIZEPfPngQ0ITqV4j1J4bnifiNVhynnR7Y+0TfAMLxKMSqX9yuMtf+laaO+OXtBz8hU5Wtpu1g5+KkrJk5T1fGrtVp3ulxiKhEL5oQKb5kI813R6es6kCFMoe83DPu7IC4kjSGh0xwoi6iaFtELbl86HU1g0HoCpcgB0AFV/IbtSAGl1wI8Cd8Gma0=
