language: python
script:
- echo $FOO
env:
  global:
    secure: GHIoClmMzqgzpTc8u3sXo1jaA0IKE/hgIu0EcqQFaI9VYYvnsV/+xZ73Idc11mVTtK42yU5JJhbClM7UEGBxoocuVeijTa87utUNMiDwutww8h36AM0aqkaIlqUezRSHaNmUB2CZXBVwOc5bk3SvGIykUiqO8VqxIiOjR1nH/wJhIRxs9I6uO8pzDL/Fyk12K+JEPe+Ko31qworOU4sSQ+dnJdtLkALVJn6erMNKrlKknWsBIVOsT4ZOFiew8Uv/VMMMoDC2/cDrhaYwmGe1u9eYSe+t6cSCPXCj9vz0ncPlXAK4Q6rKAnR7YIeJS9eyRi1jFBRvqOD2nEnePpFZ37oP89t0VxNxSp+PwWaCjwtZGCfZXTkqHzPFvh4R2f+b1nVoLedf+rtyfYF6EDgwgIVeHa08Tfr125q5PaZRsw+yWwCQgrwOV44Gm5irfDZfQ5MEExAbA5K0lqGse/bwH9NtHj6CVmVFujzwxk5olLg4efC3BRKRZDhRlOWyVqEvGFGeAyUc2xDr7eELmH4kszbUD91wm9nJaSS+rbv3tBj/w3X5JFXjLn93xtWTXtts4/brfUEUM/Qo8ow8p1s7b+ER0t/QpKclMwuJUW25MnSyo9ccNmmg+b1LtPpP1J1Dxqj6MgsQUHqAI+p6d/AAiTp+l4FXYiSt5swALWHFSGA=
