language: python

script:
  - echo hi

env:
  global:
    secure: hf7wnp1MEH5iWSkQYCbKcBbY6/X1bvsfyamply1DmmZXn/LRNm5DRlQ47jcCZFKBiGYI8fpkCN/b7XqWImkzOZ2TmFlj9chCcwS0Gu7NcvLeYBYQQev4jbZSc1TaOEhnNt43FSO+9sqMuY8IBG/sVI8NM7oXeCR+KSeqO4ThR73eEtDMm4xY/IOdjB9yXLZeIFAZcDc1kEMlKd/CmIAupdR1XPhuuyj3MeElbLxJx83M/Nv3J9y5QOZ2E9qHx+SWoquCsdcpvZ38oJFNaNPXk+eqF62l4aqXNBEkhStMdyDcdo64Lcd031UnBcsYQH74sOv/Ng6g3Tc0Z9TRYeoHkypR5elfVw9nEraBdlc096K4rgSImC1ng+M+9I6AvASDMhEqMAN3YbXXKj14SVUONNa5DTXZzQa5ogSNtGG41NfNja9b54+7wzdCjE1sf2Liks/CyAgt6Jo9YXxHPxwkP0mMj+V7kZyJn7I7UclfmXKk4Vzb6PaQHHC+zL5YJfWft/+Pv7ukLxSIQUa+jbmIBNf3gnGY3g2i/zcq4Kk4gwMLG52e0bDcert/N57YEzQvJiJv9E3gAfgeslsJysA8D2UYlCWtak31NERw5mX22xg3rzkGLLZPzHABJa1LSVVrA/Kc6mGeqceCuMWeNb/yeQv1OnNTeO/hzdbcB13XOhg=
