language: python
script:
- echo hi
env:
  global:
    secure: pj9HKttLOBbq/lrc0fJPfPcLzPbnCF0R3Py9IeDrYOCgWL41LN8m9R7HlMxuK/Tl6+R7vdnxEL/G3mNeK8a+qRprIIXIcZu9f3dx3aMbp4La69difNF10z62OVqg5G6CrDFG4dhHAKS4EjxPt3sllSi7TOAr+yBbRBkU2IW8VJ1oKJx1oDtBHdPrMA4TR+TTp5G3XXxp2h8D/RCFZHNMmgP+R4I65ldvK7MEXDyYo9zEHdGIscFRzomMVldSN8wK9xm4IxrSS9qdFdQA/OR+dbdGvYgJ5f54Y7n6GLHOifT/n9dnscSpSw8AysyNXkTtD1wHarO/kPgBMp8wzzlzj2dn1UvsvXs6RH50eX93+zvhip5dEPfEJwOx6WlZ3vbMlz4XYWhLN5oHndjzDwns6YxQ+qn2MOm9wSlbC0PXa7ZvN8EOFX4ERUtV65O8Iy7QUy8GGE+tDD++64MCkcZjqW+csacV2x5gmqHmTlwZlkcRTLR2ylL/bjge8KkrmrdzowoSqT21zItdANls4tpnn9fWPQzKmWoACKOyCUEiMH8yj+cRXN6VV2GE6TLHEfvNe1YADgMq/jrRUZxoY9EvoNfOr5/KfJmeLhnohrgQWsmlPLKLfJxVff8lfImHnRX75ixNRE+4nyxDqleydFHQySOkIvfkRnDMdYzuLCxUCO0=
