language: python
script:
- echo $FOO
env:
  global:
    secure: ccOQQDYG0vqT9vzm6WXNnQghgdhG8QzgdtBS/hYPndTIVdVAAus9TXDRP6+LyJdPU6hjJvVX3MCjMY9K0PCzKaheRmR2qoimw4Jzp27zYeR1w/3OjopQzm294nksyOPd6k5dXVEBa2fhyh7iJ7cz1zDmZIlDCbWw5fJKCb22Isk+ENdiYMHCDcVwV9tc2Nj1Q2NMr7LmxBJSoFAposSdB2ZMpvMxtR95D73vdBS8ApvN31so3Dg+4S6XBxy+s+96xH5mzvQkF0hbDBK9taWC3nylJA1ipmInDk2M9xxtOluZxgrRjh321ZhtX9iIsIPkxU39YwRAGpe23IgxHRj85wMJbZoQraPNdwTtJp8HSQl4D2eycvF6TxNhj7Wbh7ZJfpZEM5l8jdf9K2qD8voIZMk4/IZ6olF7fDR5HrRnJs3bwbWfw/ZoCHAa1EBpJeBh7G2tK/2m1ejtH6IWRxCO0MsmAzaMQmD1NXfgsCTVGpUlluICf01DhcJVkGVKOffNiZMIeSl22VYjjKyt7up75b9YdoWUeZPM80oYxZR4GyQkiEMctU2Kxh5WXtbHWRaIGbHs6bl0g5jFN+qhtgDphj3TEvhUaG5y+GgTvDlh38vsvDlGAXJCOspH32JT3U+P8Jf45zMVixdGqqh3JR9NgxDNx8sdXIFd10cktD7xQ80=
