language: python
script:
- echo $FOO
env:
  global:
    secure: LjK5CSi9vHfKA00kQ/v+rVpiT8ou1Fgbg24ZQKUQBDOB1ZwCkNahmUTMvvfu/DwMc2AMyjFD3w6Zoh44tieOC7RqBDnSrgDb0uBRazzAiMDngECbR12vZLwerOFEku86bZiqyTH9/e99Gee8hfXpxMn2jM/LmlboEAtK7Ytdn/dEPm8PuSHr25f+fJJMveUG6FHzMFvzgqTEX9zOTHF9xo7DbHft1Iz2XH889CY1YIKKnVYwKrwKnIAkBuRaDn78zFjlTjgNeC2550AIpazqogbG00rOw3rCrU1ynsW2fm8R3H9sUOVY8l6jAGvilsSGRkx6/iCcM5+zMJHBYvP7avXCnkPA5k3OP62Q0bGXr/OCeLrsZLw3+1Am5amvH/GbHY4nu16w/4kUhSVQmqIgxEkWY+HTWbUWCMFvph9FJEw/jamiLkOWV6XGUivuZEo+2RCQYzwXa95QYU0JGGhN/C3jeSWC/MZtPjPwGWrlQtuGU7ONGDkcabgfFtjJOlNne00qJpBzPrDk9Ybq7vUxTbKrzS8oUkQKWvJx/1Qyop+6XyRdgMzkHGdjT6SGBuuuTF8682Vafd767ujCxSPhlgJMKEkg61EiZ0iMfMv1lVeJnl2dHptSmrKundKtTDW3mwmP1vnf8vWhqyfns8rRvwY/s11OP/mY4XFXjnbzQYY=
