language: python
script:
- echo hi
env:
  global:
    secure: SQ4tjIcl4+TBc37PTLUtsx77qLcaE9lFDALs/loptaSdqr/qo2YW4HYQQ4CIXtXfsyMgSYVmoZaNNXIc0Y6SgXhewc1vrwlQE4bbmCsyGkdGFDVg2M84uQe9PBToBAsPyCk/mr33lgcNQufSBS8EeaQlhO7KLHaHvVJyD41SJUZiQXLZKry3UwXatll2x//NQ0ny1hQG+H/QCnJcYlGzsG6/OEYPyaBlkJyAlAooRp3cuZu0gx6EmN9FBJTI6arKGb5xA4NeyCuWlq+/QtpAjzmT5xQGm2rT+XQvXjMhUnH6Z0YeQpmMvVNLoKah3ovS+rWMvFURpzpDy6TbsP1whqAbW50cYk3wnO37diLb2gq/owZodq9S8NfgdKhMeGmqfCA2TodHQHD5Ko5LsexCADGGprEJmiyZklfGF+jRtf38t2UwoKhJekN9I3yJEXJdn+MrcQxSiLgb9qwMBeuJQjx6Im20VBKTbVa3pxGUk3M9yUNNgOpBttisLd0uyh3Q5G3WdRLqKBImHyesxrGJTJlc1MyYhShRJ5BFWfgx8f/L+rCGSHf34jRiIc2o2J9QoIAFlxFncuW9bGTtQsLAR9/lA4JDFQ4HyzJ4YYNaX34JyQRMKAjJzI9bOVny2O/WyhNb60yrTSt0e0lBmyuqpjjHNg0VADkMUzI5FJy23hM=
