#!/usr/bin/env bash
set -e

HINT_DIR="$HOME/.hint"
mkdir -vp "$HINT_DIR"
rm -rf "$HINT_DIR/bin"
rm -rf "$HINT_DIR/lib"
cp -vr bin "$HINT_DIR"
cp -vr lib "$HINT_DIR"

echo "
Add the following to your shell config:
  export PATH="\$HOME/.hint/bin:\$PATH"
"
